intro_hed_name:	dc.b	"INTRO.JHD",0
intro_gfx_name:	dc.b	"INTRO.JSP",0
font1_hed_name:	dc.b	"FONT1.JHD",0
font1_gfx_name:	dc.b	"FONT1.JSP",0
circ_name:	dc.b	"CIRC.BIN",0
sine_name:	dc.b	"SINE.BIN",0    
logo_hed_name:	dc.b	"LOGOS.JHD",0
logo_gfx_name:	dc.b	"LOGOS.JSP",0
atari_pal_name:	dc.b	"ATARI.JPL",0
idi_pal_name:	dc.b	"IDI.JPL",0
waterfon_pal_name:	dc.b	"WATERFON.JPL",0
title_gfx_name:	dc.b	"TITLE.PIC",0
title_pal_name:	dc.b	"TITLE.CPL",0
title_rgb_name:	dc.b	"TITLE.RGB",0
star_pal_name:	dc.b	"STAR.JPL",0
bubsy_pal_name:	dc.b	"BUBSY.JPL",0
intro_mod_name:	dc.b	"TITLE.MUS",0
hi_mod_name:	dc.b	"HIGH.MUS",0
	even

