	xref.l	INIT_SOUND
	xref.l	PT_MOD_INIT
	xref.l	FADEUP
	xref.l	FADEDOWN
	xref.l	NOFADE
	xref.l	SET_VOLUME
	xref.l	START_MOD
	xref.l	STOP_MOD
	xref.l	PLAYFX
	xref.l	NT_VBL
	xref.l	RESUMEDSP
	xref.l	HALTDSP
	xref.l	DISABLE_FX
	xref.l	ENABLE_FX

	xref.l	STARTGPU
	xref.l	STOPGPU
	xref.l	GPUPP_S
	xref.l	GPUPP_E
	xref.l	SETUPGPU
	xref.l	DECOMPRESSGPUPP1
	xref.l	WAITFORGPU
	xref.l	GETSAMNO
	xref.l	SET_VOLU
	xref.l	GPUSEMAPHORE

	xdef.l	DISABLETIMER
	xdef.l	ENABLETIMER
