		even
		include aistuff\global\bananaai.s			;ok
		even
		include aistuff\global\birdsai.s			;check offsets
		even
		include aistuff\global\bubbleai.s			;ok
		even
		include aistuff\global\contai.s			;ok
		even
		include aistuff\global\crateai.s			;ok
		even
		include aistuff\global\deleteai.s			;ok
		even
		include aistuff\global\endingai.s
		even
		include aistuff\global\gamovrai.s
		even
		include aistuff\global\midptai.s			;ok
		even
		include aistuff\global\recycai.s			;ok
		even
		include aistuff\global\shirtai.s			;ok
		even
		include aistuff\global\smokeai.s			;ok
		even
		include aistuff\global\splashai.s			;ok
		even
		include aistuff\global\superyrn.s			;ok
		even
		include aistuff\global\tackai.s			;ok
		even
		include aistuff\global\winai.s
		even
		include aistuff\global\yarnai.s			;ok
		even
		include aistuff\global\duckai.s			;ok i think
		even
		include aistuff\global\lvltxtai.s
		even
		include aistuff\global\arrowai.s			;ok
		even
		