		include	aistuff\alice\vulture.s
		include	aistuff\alice\ginger.s
		include	aistuff\alice\waspai.s
		include	aistuff\alice\snake.s
		include	aistuff\alice\catai.s
		include	aistuff\alice\cardai.s
		include	aistuff\alice\flamai.s
		include	aistuff\alice\rabbit.s
		include	aistuff\alice\switches.s
		include	aistuff\alice\doorai.s
		include	aistuff\alice\tdeedum.s
		include	aistuff\alice\hatterai.s
		even
			